name: nerf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - pytorch>=1.6
  - cuda100
  - cudatoolkit>=10.1
  - cudatoolkit-dev
  - imageio
  - numpy
  - pyyaml
  - tensorboard
  - torchvision
  - tqdm
  - pip:
    - opencv-python-headless
